// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj0EWZi9SLq_JiSXyze66m29hsvRRUCho',
    appId: '1:318362878284:web:80bbef0ae37003ffc40fe9',
    messagingSenderId: '318362878284',
    projectId: 'chat-app-eb0bb',
    authDomain: 'chat-app-eb0bb.firebaseapp.com',
    storageBucket: 'chat-app-eb0bb.appspot.com',
    measurementId: 'G-R50NKESCE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-IkqkmFgSCoVbBL15YgFS8NtFgNMW3_4',
    appId: '1:318362878284:android:b9633654ecbd49ffc40fe9',
    messagingSenderId: '318362878284',
    projectId: 'chat-app-eb0bb',
    storageBucket: 'chat-app-eb0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTVRCjqccNV6Tr3qaOKU54yASJQwZSDWU',
    appId: '1:318362878284:ios:b7264135174dae5ac40fe9',
    messagingSenderId: '318362878284',
    projectId: 'chat-app-eb0bb',
    storageBucket: 'chat-app-eb0bb.appspot.com',
    iosClientId: '318362878284-qpdrcltj2666pomin57tecmru35sbcd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTVRCjqccNV6Tr3qaOKU54yASJQwZSDWU',
    appId: '1:318362878284:ios:b387ad00919dde6cc40fe9',
    messagingSenderId: '318362878284',
    projectId: 'chat-app-eb0bb',
    storageBucket: 'chat-app-eb0bb.appspot.com',
    iosClientId: '318362878284-o202oc92e651obdrtrf84ivkqchh1o6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
